services:
  lka-app:
    build: .
    container_name: lka-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - lka-db
    volumes:
      - ./config:/var/www/lka/config
      - ./docker/sites:/etc/apache2/sites-available
      - ./docker/certs:/etc/apache2/certs

  lka-db:
    image: mariadb:10.11
    container_name: lka-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data: